export const questions = [
  {
    id: 1,
    title: 'diff two array',
    slug: `diff-two-array`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 100,
    isPremium: false,
  },
  {
    id: 2,
    title: 'selection sort',
    slug: `selection-sort`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 100,
    isPremium: false,
  },
  {
    id: 3,
    title: 'binary sort',
    slug: `binary-sort`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'medium',
    points: 200,
    isPremium: false,
  },
  {
    id: 4,
    title: 'quick sort',
    slug: `quick sort`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'medium',
    points: 200,
    isPremium: true,
  },
  {
    id: 5,
    title: 'merge sort',
    slug: `merge sort`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
  },
  {
    id: 6,
    title: 'find the symmetric difference',
    slug: `find-the-symmetric-difference`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
  },
  {
    id: 7,
    title: 'inventory update',
    slug: `inventory-update`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
  },
  {
    id: 8,
    title: 'no repeats please',
    slug: `no-repeats-please`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
  },
  {
    id: 9,
    title: 'pairwise',
    slug: `pairwise`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
  },
  {
    id: 10,
    title: 'diff two arrays',
    slug: `diff-two-arrays`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 11,
    title: 'dna pairing',
    slug: `dna-pairing`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 12,
    title: 'drop it',
    slug: `drop-it`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 13,
    title: 'everything be true',
    slug: `everything-be-true`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 14,
    title: 'missing letters',
    slug: `missing-letters`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 15,
    title: 'pig latin',
    slug: `pig-latin`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 16,
    title: 'sorted union',
    slug: `sorted-union`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 17,
    title: 'sales by match',
    slug: `sales-by-match`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 18,
    title: 'counting valleys',
    slug: `counting-valleys`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 19,
    title: 'jumping on the clouds',
    slug: `jumping-on-the-clouds`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 20,
    title: 'repeated string',
    slug: `repeated-string`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 21,
    title: '2D array - DS',
    slug: `2D-array-DS`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 22,
    title: 'arrays: left rotation',
    slug: `arrays:-left-rotation`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'easy',
    points: 300,
    isPremium: true,
  },
  {
    id: 23,
    title: 'new year chaos',
    slug: `new-year-chaos`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'medium',
    points: 300,
    isPremium: true,
  },
  {
    id: 24,
    title: 'minimum swaps 2',
    slug: `minimum-swaps-2`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'medium',
    points: 300,
    isPremium: true,
  },
  {
    id: 25,
    title: 'array manipulation',
    slug: `array-manipulation`,
    problem: '',
    inputFormat: '',
    outputFormat: '',
    questionSeed: '',
    level: 'hard',
    points: 300,
    isPremium: true,
  },
];
