apiVersion: apps/v1
kind: Deployment
metadata:
  name: questions-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: questions
  template:
    metadata:
      labels:
        app: questions
    spec:
      containers:
        - name: questions
          image: keiracle/questions
          env:
            - name: POSTGRES_HOST
              value: questions-postgres-srv
            - name: POSTGRES_DB
              value: "questions_service"
            - name: POSTGRES_PASSWORD
              value: "12345678"
            - name: JWT_SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET_KEY
          resources:
            limits:
              memory: "512Mi"
              cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: questions-srv
spec:
  selector:
    app: questions
  ports:
    - name: questions
      protocol: TCP
      port: 3000
      targetPort: 3000
