export const easyChallenges = [
  {
    title: 'Two Sum',
    slug: 'two-sum',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a, b) => {}',
  },
  {
    title: 'Palindrome Number',
    slug: 'palindrome-number',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Roman to Integer',
    slug: 'roman-to-integer',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Longest Common Prefix',
    slug: 'longest-common-prefix',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Valid Parentheses',
    slug: 'valid-parentheses',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Merge Two Sorted Lists',
    slug: 'merge-two-sorted-lists',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Remove Duplicates from Sorted Array',
    slug: 'remove-duplicates-from-sorted-array',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Remove Element',
    slug: 'remove-element',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Search Insert Position',
    slug: 'search-insert-position',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Length of Last Word',
    slug: 'length-of-last-word',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Remove Duplicates from Sorted List',
    slug: 'remove-duplicates-from-sorted-list',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Climbing Stairs',
    slug: 'climbing-stairs',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
  {
    title: 'Binary Tree Inorder Traversal',
    slug: 'binary-tree-inorder-traversal',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
];

export const mediumChallenges = [
  {
    title: 'Binary Tree Inorder Traversal',
    slug: 'binary-tree-inorder-traversal',
    point: 100,
    level: 'Easy',
    seed: 'const main = (a) => {}',
  },
];
